export type GuideModuleDetail = {
  id: string;
  sectionId: string;
  title: string;
  path: string;
  badge: 'Editor' | 'Admin only' | 'Public';
  why: string;
  when: string[];
  how: string[];
  publicRoutes: string[];
  dbTables: string[];
  seeds?: string[];
};

/** Detailed why / when / how for every admin module. */
export const GUIDE_MODULE_DETAILS: GuideModuleDetail[] = [
  {
    id: 'dashboard',
    sectionId: 'operations',
    title: 'Dashboard',
    path: '/admin',
    badge: 'Editor',
    why: 'Gives operators a single health view — catalog volume, new leads, CMS page count — and a first-run checklist so nothing critical is missed before go-live.',
    when: [
      'First login after schema import or db:import',
      'Weekly content/lead health checks',
      'Before handing the site to marketing (verify checklist complete)',
    ],
    how: [
      'Review stat tiles: catalog items, published count, new enquiries, CMS pages, media assets',
      'Work through Setup checklist — each row links to the module and offers a Seed action',
      'Admins: click Bootstrap missing seeds to run all missing seeds in one pass',
      'Use Quick actions to jump to high-traffic modules',
    ],
    publicRoutes: ['Indirect — bootstrapped content appears on the public site after seeds run'],
    dbTables: ['pages', 'page_sections', 'nav_items', 'catalog_items', 'media_assets', 'enquiries', 'form_fields', 'theme_settings'],
    seeds: ['POST /api/admin/setup/bootstrap (admin only) — home, inner pages, nav, catalog, subject field, site settings'],
  },
  {
    id: 'pages',
    sectionId: 'content',
    title: 'Pages',
    path: '/admin/pages',
    badge: 'Editor',
    why: 'Marketing and legal content must change without code deploys. Pages drive the homepage, contact, careers, certifications, and custom landings.',
    when: [
      'Edit homepage sections (hero, stats, industries, testimonials)',
      'Create or update contact, careers, privacy, terms',
      'Add a custom landing page at a new slug (e.g. /about)',
      'Preview draft content before publishing',
    ],
    how: [
      'List pages → open a page → edit SEO (title, description, OG), slug, status',
      'Section editor: add, reorder (↑↓), duplicate, or clear sections',
      'Pick section type (25+ types) — use typed forms or JSON mode for advanced edits',
      'Media picker on image fields; style_json for extra CSS class/scoped rules',
      'Preview → signed URL (?preview=1&token=…) valid 12 hours',
      'Set status Published when ready; draft pages stay hidden on public site',
    ],
    publicRoutes: ['/', '/contact', '/careers', '/certifications', '/privacy', '/terms', '/industries', '/{custom-slug}', 'GET /api/public/pages/[slug]'],
    dbTables: ['pages', 'page_sections'],
    seeds: ['Seed homepage', 'Seed inner pages (contact, careers, certifications, privacy, terms)', 'Seed industries (hub + landing stubs)', 'Dashboard bootstrap'],
  },
  {
    id: 'inventory',
    sectionId: 'content',
    title: 'Inventory',
    path: '/admin/inventory',
    badge: 'Editor',
    why: 'Projects, products, and services are the commercial core — they power listings, case studies, search, and enquiry context.',
    when: [
      'Add a new product, project reference, or service offering',
      'Build a premium case study page with gallery and enquiry form',
      'Set featured items for homepage teaser or catalog hero spotlight',
      'Attach brochure PDF or video for gated download',
    ],
    how: [
      'Select tab: Projects | Products | Services',
      'Create manually or Seed {type}s (Zigma catalog samples)',
      'Fill title, slug, summary, description, category, tags, specs',
      'Complete Case study block: client, sector, location, challenge, solution, outcomes, testimonial, before/after',
      'Media modal: upload, attach from library, reorder, set ★ card thumbnail',
      'Set Status Published, Enabled, Featured as needed',
      'Re-seed: Delete all {type}s first, then Seed again',
    ],
    publicRoutes: ['/projects', '/products', '/services', '/projects/{slug}', '/products/{slug}', '/services/{slug}', 'GET /api/public/catalog/[type]', 'GET /api/public/catalog/[type]/[slug]'],
    dbTables: ['catalog_items', 'catalog_media', 'catalog_categories'],
    seeds: ['POST /api/admin/catalog/seed per type', 'Dashboard bootstrap seeds all three types'],
  },
  {
    id: 'catalog-settings',
    sectionId: 'content',
    title: 'Catalog Settings',
    path: '/admin/catalog-settings',
    badge: 'Editor',
    why: 'Same inventory data can present differently per client or campaign — layout, hero, filters, and visual preset without re-entering items.',
    when: [
      'After seeding inventory — tune listing UX',
      'Switch visual preset for a rebrand (premium, glass, bold-corporate)',
      'Configure hero spotlight rotation for featured projects/products',
      'Enable/disable search, category filter, tag filter, skeleton loading',
    ],
    how: [
      'Select item type (project / product / service)',
      'Choose visual style preset and hero variant (standard / spotlight)',
      'Configure hero copy (blank fields show the default in grey), rotation timer, and selected spotlight items',
      'Page sections: order the hero, listing and partner strip; partner strip titles need Site Copy access',
      'Set grid vs list, column count, card fields, modal sections',
      'Toggle appearance: skeleton loading, reveal animation, premium borders',
      'Save — changes apply on next public page load',
    ],
    publicRoutes: ['/projects', '/products', '/services — listing chrome and hero'],
    dbTables: ['catalog_page_settings (one row per item_type)'],
    seeds: ['Default rows inserted by scripts/schema.sql'],
  },
  {
    id: 'resources',
    sectionId: 'content',
    title: 'Resources',
    path: '/admin/resources',
    badge: 'Editor',
    why: 'Technical guides and checklists build SEO authority and support sales conversations with practical engineering content.',
    when: [
      'Publish UPS sizing, solar O&M, or BESS guides',
      'Add checklist content linked from tools or consultation flows',
      'Tag content for filtered hub views (/resources?tag=Solar)',
    ],
    how: [
      'Create post or Seed samples (UPS, Solar O&M, BESS)',
      'Set title, slug, excerpt, HTML body (use h2, lists, blockquote for premium layout)',
      'Add cover image, tags, meta title/description',
      'Set status Published and enabled',
    ],
    publicRoutes: ['/resources', '/resources/{slug}', 'GET /api/public/resources', 'Article JSON-LD'],
    dbTables: ['resource_posts'],
    seeds: ['POST /api/admin/resources/seed', 'Requires scripts/migrate-resource-posts.sql'],
  },
  {
    id: 'press',
    sectionId: 'content',
    title: 'Press',
    path: '/admin/press',
    badge: 'Editor',
    why: 'Company announcements, certifications, and milestones need a dedicated newsroom separate from long-form guides.',
    when: ['Publish a press release or milestone', 'Link to external source article', 'Pair with Site Copy hub text for /press'],
    how: ['Create/edit post with title, slug, excerpt, body HTML, cover', 'Optional source_name and source_url', 'Publish when ready'],
    publicRoutes: ['/press', '/press/{slug}'],
    dbTables: ['press_posts'],
    seeds: ['POST /api/admin/press/seed', 'Requires scripts/migrate-wave3.sql'],
  },
  {
    id: 'testimonials',
    sectionId: 'content',
    title: 'Testimonials',
    path: '/admin/testimonials',
    badge: 'Editor',
    why: 'Social proof on contact and CMS sections increases conversion. No review/rating JSON-LD is emitted — Google treats first-party testimonials as self-serving; collect ratings on Google Business Profile instead.',
    when: ['Add real client quotes after project delivery', 'Feature a quote on contact page strip', 'Seed samples for demo environments'],
    how: ['Create testimonial: author, role, company, rating, quote', 'Set published and optionally featured', 'Verify on /contact and homepage testimonial section'],
    publicRoutes: ['/contact (strip)', 'GET /api/public/testimonials'],
    dbTables: ['site_testimonials'],
    seeds: ['POST /api/admin/testimonials/seed', 'Requires scripts/migrate-testimonials.sql'],
  },
  {
    id: 'site-settings',
    sectionId: 'configuration',
    title: 'Site Settings',
    path: '/admin/site-settings',
    badge: 'Editor',
    why: 'Single source of truth for company identity, contact channels, address and analytics — wired into Header, Footer, email, and JSON-LD.',
    when: [
      'Launch or rebrand (logo, company name, phones, emails)',
      'Enable GA4 / Plausible, cookie consent, SLA metrics',
      'Edit the cookie banner and /cookies page wording',
      'Set thank-you booking URL, WhatsApp number, header CTA',
      'Configure sticky mobile bar & floating CTAs (add/edit/hide/reorder)',
    ],
    how: [
      'Edit company profile, logo URL, logo alt',
      'Header & Footer → Header: logo chip & word type, navigation menu style & fonts, header CTA, Talk to us, sticky mobile & floating CTAs',
      'Header & Footer → Footer: footer brand (.foot-brand), office block layout, blurb, copyright, Powered by credit, legal links',
      'Address & office — postal address, office hours / SLA values; used by the footer, JSON-LD, contact/thank-you/SLA',
      'Social links (Facebook, Instagram, LinkedIn, X, YouTube) — blank hides; footer icons + JSON-LD sameAs',
      'Analytics & cookies — GA4 / Plausible IDs, consent switches, cookie banner and /cookies text (text needs Site Copy access)',
      'Elsewhere: default meta description and share image in SEO → Defaults; CRM webhook in Forms & CRM → CRM; enquiry notify list in Email → Variables',
      'SLA metrics JSON for /sla dashboard; A/B header CTA variant',
      'Save — public site reads via GET /api/public/site-settings',
    ],
    publicRoutes: ['Header, Footer, JSON-LD, mail, CRM, /thank-you, /sla', 'GET /api/public/site-settings'],
    dbTables: ['theme_settings (key: site)'],
    seeds: ['Dashboard seed-site-settings → DEFAULT_SITE_SETTINGS'],
  },
  {
    id: 'site-copy',
    sectionId: 'configuration',
    title: 'Site Copy',
    path: '/admin/site-copy',
    badge: 'Admin only',
    why: 'White-label deployments need marketing strings, hub heroes, modal copy, and feature flags without changing React components — critical for multi-client template reuse.',
    when: [
      'Onboarding a new client after db:import',
      'Toggle tools (/tools/*), locales (/hi, /kn), or partner portal',
      'Edit calculator copy and hub page heroes',
      'Update industries/locations hub JSON content',
    ],
    how: [
      'Navigate tabs: Hubs, Features, Hero height, Tools, Locales (header/footer labels: Header & Footer → Labels; built-in page titles: SEO → Page titles; enquiry pop-up and thank-you page: Forms & CRM; catalog page headings and partner strip: Catalog Settings; cookie banner and /cookies text: Site Settings → Analytics & cookies)',
      'Edit strings; save each section (PUT requires admin role)',
      'Feature flags: toolsEnabled, localesEnabled, partnersEnabled',
      'Industries/locations JSON drives /industries and /locations pages',
    ],
    publicRoutes: ['All chrome surfaces', 'GET /api/public/site-copy'],
    dbTables: ['theme_settings (keys: site_copy, industries, locations)'],
    seeds: ['New Client wizard resets to DEFAULT_SITE_COPY'],
  },
  {
    id: 'navigation',
    sectionId: 'configuration',
    title: 'Header & Footer',
    path: '/admin/header-footer',
    badge: 'Editor',
    why: 'One place for the site frame: mega-menu and footer link trees, header/footer settings and their labels — editable by marketing without deploys.',
    when: ['Launch — seed header/footer', 'Add new section to mega-menu after new hub page', 'Rebrand — update footer legal/social links', 'Reset corrupted nav: Clear then Seed'],
    how: [
      'Tabs: Menus (nav trees), Header and Footer (site settings), Labels (site copy) — each tab needs that screen’s permission',
      'Menus: select Header or Footer',
      'Seed tree (or Clear then Seed to reset)',
      'Add nested items: parents → columns → links',
      'Reorder siblings with ↑/↓; delete cascades to children',
      'Public Header/Footer read nav_items via loadSiteShell; Footer has NO hardcoded fallback — empty Admin Footer = empty link columns',
    ],
    publicRoutes: ['Header, Footer components', 'GET /api/public/nav'],
    dbTables: ['nav_items (location: header | footer, parent_id, meta_json)'],
    seeds: ['POST /api/admin/nav/seed { location: header | footer }', 'Data from src/lib/nav-seed.ts'],
  },
  {
    id: 'theme',
    sectionId: 'configuration',
    title: 'Theme Studio',
    path: '/admin/theme',
    badge: 'Admin only',
    why: 'Brand theming (colours, typography, custom CSS) without editing globals.css — supports client-specific visual identity and live preview.',
    when: ['Rebrand colours or fonts', 'Client-specific CSS overrides', 'Publish draft CSS after review'],
    how: [
      'Colours & layout tab: brand / neutral colours, section padding, header height → Save tokens',
      'Typography tab: type scale, heading levels and eyebrow sizes → Save typography (levels and eyebrows are site settings)',
      'Site CSS tab: edit draft → Save draft → Publish',
      'Email accent follows the Orange brand colour unless Email → Settings sets its own',
      'Optional sync to disk (sync_files)',
      'Public site loads /api/public/theme.css in root layout',
      'ThemePreviewBridge shows live preview while editing',
    ],
    publicRoutes: ['GET /api/public/theme.css (tokens + published css_overrides)'],
    dbTables: ['theme_settings (keys: tokens, site for heading levels / eyebrow sizes)', 'css_overrides'],
    seeds: ['New Client can reset tokens to DEFAULT_THEME_TOKENS'],
  },
  {
    id: 'new-client',
    sectionId: 'configuration',
    title: 'New Client',
    path: '/admin/new-client',
    badge: 'Admin only',
    why: 'Accelerates white-label onboarding: apply brand details, reset Site Copy, optionally seed demo content on a cloned CMS snapshot.',
    when: ['After db:import on a fresh environment for a similar vertical client', 'Demo environment setup', 'Rebrand from Zigma defaults to client brand'],
    how: [
      'Enter company name, phones, email, tagline',
      'Toggle reset Site Copy and/or theme tokens',
      'Optional: seed demo content (runs full bootstrap)',
      'Continue in Theme Studio and Site Copy; replace logo/media',
    ],
    publicRoutes: ['Updates all public surfaces via theme_settings'],
    dbTables: ['theme_settings (site, site_copy, tokens); optionally all seeded tables'],
    seeds: ['Optional seedDemoContent → POST /api/admin/setup/bootstrap'],
  },
  {
    id: 'enquiries',
    sectionId: 'leads',
    title: 'Enquiries',
    path: '/admin/enquiries',
    badge: 'Editor',
    why: 'Single triage inbox for all inbound interest — contact, catalog, careers, callback — with notes, status workflow, and secure resume access.',
    when: ['Daily lead handling', 'Download careers resume', 'Export CSV for CRM import', 'Add internal notes before closing'],
    how: [
      'Filter by status: new → in_progress → closed',
      'Search payload JSON for name, email, subject',
      'Open row → review payload; add admin notes',
      'Careers: download resume via secure admin endpoint (not public URL)',
      'Export CSV (?format=csv) for CRM',
    ],
    publicRoutes: ['Fed by POST /api/public/enquiries, /api/public/careers/apply, /api/public/callback'],
    dbTables: ['enquiries (payload_json, status, admin_notes, form_definition_id, catalog_item_id)'],
    seeds: ['Populated by public submissions only'],
  },
  {
    id: 'forms',
    sectionId: 'leads',
    title: 'Forms & CRM',
    path: '/admin/forms',
    badge: 'Editor',
    why: 'Everything about collecting leads in one place: the shared enquiry form, the pop-up and thank-you text visitors see, and which submissions are forwarded to your CRM.',
    when: [
      'Add enquiry subject dropdown options',
      'Reorder fields for UX',
      'Reword the enquiry pop-up or thank-you page',
      'Connect HubSpot / Zoho / Zapier and choose which leads it receives',
    ],
    how: [
      'Form fields tab: edit the default form (enquiry_default) — reorder ↑/↓, edit label, placeholder, options, required, enabled',
      'Dashboard Seed on subject row adds subject select field',
      'Pop-up & thank-you tab (Site Copy permission): pop-up title / lead / button labels and every /thank-you text',
      'CRM tab (Site Settings permission): webhook URL, secret, which kinds to send (enquiries, callbacks, brochures, job applications, newsletter), and a test send',
      'Each tab appears only for roles with its permission',
    ],
    publicRoutes: [
      'GET /api/public/forms/enquiry',
      'Home consultation modal, contact page, catalog enquiry modals, /thank-you',
      'CRM webhook: POST to your URL after each enabled submission',
    ],
    dbTables: ['form_definitions', 'form_fields', 'theme_settings (site copy, site settings)'],
    seeds: ['Schema inserts default fields', 'Dashboard seed-subject'],
  },
  {
    id: 'newsletter',
    sectionId: 'leads',
    title: 'Newsletter',
    path: '/admin/newsletter',
    badge: 'Admin only',
    why: 'Footer subscribe captures marketing list; admin export feeds email tools or CRM.',
    when: ['Review new subscribers', 'Export list for campaign', 'Remove spam entries'],
    how: ['View subscriber list', 'Export or delete entries', 'Footer form posts to POST /api/public/newsletter'],
    publicRoutes: ['Footer subscribe → POST /api/public/newsletter'],
    dbTables: ['newsletter_subscribers'],
    seeds: ['None'],
  },
  {
    id: 'media',
    sectionId: 'media-seo',
    title: 'Media',
    path: '/admin/media',
    badge: 'Editor',
    why: 'Upload once, reuse across CMS sections and inventory — avoids duplicate assets and broken URLs.',
    when: ['Upload brand photography or diagrams', 'Pick images in section editors (Browse media)', 'Set alt text for accessibility and SEO'],
    how: [
      'Upload JPEG/PNG/WebP/GIF/SVG/MP4/WebM',
      'Files stored under public/assets/{images,svg,video}',
      'Library merges DB rows + disk scan (seeded static images appear automatically)',
      'Edit alt/tags; copy public URL; use in MediaPicker',
      'Note: visitor resumes are NOT in media library — blocked from direct access',
    ],
    publicRoutes: ['/assets/images/…', '/assets/svg/…', '/assets/video/…'],
    dbTables: ['media_assets + disk scan (src/lib/media-library.ts)'],
    seeds: ['Static seeded images appear from disk automatically'],
  },
  {
    id: 'redirects',
    sectionId: 'media-seo',
    title: 'SEO',
    path: '/admin/seo',
    badge: 'Admin only',
    why: 'One place for search and sharing: fallback description and share image, titles for built-in pages, and redirects that preserve rankings when addresses change.',
    when: ['Launch — review defaults and built-in page titles', 'Migrating from legacy public/*.html', 'Fixing broken inbound links'],
    how: [
      'Tabs: Defaults (site settings), Page titles (site copy), Redirects — each tab needs that screen’s permission',
      'Renaming the slug of a published page, resource, press post or catalog item adds a 301 from the old address automatically (and re-points older redirects to it)',
      'Redirects: from_path → to_path, HTTP status (301/302), enabled toggle; applied in src/proxy.ts (~30s cache)',
      'Legacy HTML paths also hardcoded in proxy',
    ],
    publicRoutes: ['All public paths — redirect before render', '<head> title, description, Open Graph'],
    dbTables: ['redirects', 'theme_settings (site: defaultMetaDescription, ogImage; site_copy: seo)'],
    seeds: ['None'],
  },
  {
    id: 'preview',
    sectionId: 'media-seo',
    title: 'Preview mode',
    path: '/admin/pages',
    badge: 'Editor',
    why: 'Stakeholders must review draft pages and disabled sections without publishing to production.',
    when: ['Before publishing homepage changes', 'Reviewing new custom landing page', 'Sharing draft with client for approval'],
    how: [
      'Pages → open page → Preview button',
      'Opens signed URL with ?preview=1&token=… (12h expiry)',
      'Draft pages and disabled sections visible; orange banner shown',
      'Uses PREVIEW_SECRET or falls back to AUTH_SECRET',
    ],
    publicRoutes: ['Any CMS page with preview query params'],
    dbTables: ['pages, page_sections (admin=true read path)'],
    seeds: ['None'],
  },
  {
    id: 'partners',
    sectionId: 'advanced',
    title: 'Partners',
    path: '/admin/partners',
    badge: 'Admin only',
    why: 'B2B dealer portal for price lists and documents — separate auth from admin, managed here.',
    when: ['Onboard a dealer/distributor', 'Upload partner-facing documents', 'Disable partner access'],
    how: ['Create partner user (email, password, company)', 'Upload documents', 'Optional Seed docs', 'Partners sign in at /partner/login'],
    publicRoutes: ['/partner/login', '/partner', '/api/partner/auth', '/api/partner/documents'],
    dbTables: ['partner_users', 'partner_documents'],
    seeds: ['POST /api/admin/partners seed_docs', 'Requires scripts/migrate-wave3.sql'],
  },
  {
    id: 'users',
    sectionId: 'advanced',
    title: 'Users',
    path: '/admin/users',
    badge: 'Admin only',
    why: 'Delegate content editing to editors without granting theme, redirects, or user management access.',
    when: ['Add marketing team as editors', 'Create additional admin', 'Rotate compromised credentials', 'Remove departed team member'],
    how: [
      'Add user: name, email, access (Role-based + role from Roles, or Full admin), temporary password (min 10 chars, Generate available)',
      'Edit to change name, email, access or password - changes apply on the user’s next click',
      'A new password signs the user out everywhere; Delete signs them out at once',
      'Cannot delete yourself, change your own access, or remove the last full admin',
      'First run only: Seed default admin on the login page (disabled once any account exists)',
    ],
    publicRoutes: ['None'],
    dbTables: ['admin_users'],
    seeds: ['POST /api/admin/auth/seed on /admin/login'],
  },
  {
    id: 'account',
    sectionId: 'advanced',
    title: 'Account',
    path: '/admin/account',
    badge: 'Editor',
    why: 'Security hygiene — change password after first login or when credentials may be exposed.',
    when: ['After seed admin first login', 'After db:import from shared environment', 'Periodic password rotation'],
    how: [
      'Open to every signed-in user, whatever their role',
      'Enter current password + new password (min 10 chars) → Submit; other sessions are signed out',
      'Sign out from top bar when done',
    ],
    publicRoutes: ['None'],
    dbTables: ['admin_users'],
    seeds: ['None'],
  },
];
