/** Default homepage section payloads used for seeding and fallback rendering */

export const HOMEPAGE_SEED_SECTIONS = [
  {
    type: 'hero',
    section_key: 'home',
    title: 'Hero Slider',
    content_json: {
      slides: [
        {
          theme: 'theme-legacy',
          eyebrow: '◆ EST. 2006 — TWO DECADES OF ENGINEERING',
          title: '20+ Years of Engineering Excellence',
          lead: 'Built on a Legacy of Trust. Driven by Service & Innovation. Powering industries with reliable power, solar, and engineering solutions for over two decades.',
          cta: 'Discover Our Legacy →',
          ctaHref: '#legacy',
          tags: ['Trusted Engineering Partner', 'Industrial Power Solutions', 'Reliability', 'Customer-Centric Service'],
          image: '/assets/images/zigma-technologies-engineers-monitoring-.jpg',
          numeral: '20+',
        },
        {
          theme: 'theme-ups',
          eyebrow: '◆ ZERO DOWNTIME · MISSION-CRITICAL POWER',
          title: 'Reliable Power. Preserved Productivity. Zero Downtime.',
          lead: 'Integrated UPS, battery, and power continuity solutions engineered to protect critical operations, maximize uptime, and ensure uninterrupted business performance.',
          cta: 'Explore Power Continuity →',
          ctaHref: '#protect',
          tags: ['UPS Sales, AMC & Repair', 'Industrial UPS Solutions', 'Inverter & Battery Backup', 'Power Quality Solutions'],
          image: '/assets/images/solar-farm-with-wind-turbines-at-sunset-.jpg',
        },
        {
          theme: 'theme-solar',
          eyebrow: '◆ RENEWABLE ENERGY · SUSTAINABLE FUTURE',
          title: 'Smart Solar with Sustainable Energy Future',
          lead: 'Complete Solar EPC, engineering, installation, monitoring, and long-term maintenance solutions for commercial, industrial, and utility-scale projects.',
          cta: 'Explore Solar Solutions →',
          ctaHref: '#generate',
          tags: ['Solar EPC & Power Plants', 'Rooftop, Industrial & Commercial Solar', 'Solar AMC & O&M', 'Green Energy Solutions', 'EV Charging & BESS'],
          image: '/assets/images/engineers-reviewing-electrical-design-dr.jpg',
        },
        {
          theme: 'theme-eng',
          eyebrow: '◆ ENGINEERING DESIGN & TECHNICAL SERVICES',
          title: 'Engineering Expertise Beyond Boundaries',
          lead: 'Delivering precision engineering design, technical consulting, project support, and outsourced engineering services for industrial, infrastructure, and energy projects.',
          cta: 'Explore Engineering Services →',
          ctaHref: '#experts',
          tags: ['Electrical Engineering Design', 'CAD Drafting & Documentation', 'Technical Consulting', 'Engineering Outsourcing'],
          image: '/assets/images/city-skyline-with-solar-panels-and-indus.jpg',
        },
        {
          theme: 'theme-future',
          eyebrow: '◆ SMART, SUSTAINABLE & FUTURE-READY',
          title: 'Building the Future-Ready Energy Ecosystem',
          lead: 'Building intelligent, sustainable, and future-ready power, renewable energy, and industrial infrastructure solutions for a smarter tomorrow.',
          cta: 'Talk to an Engineer →',
          ctaHref: '/contact',
          tags: ['Smart Energy & Digital Monitoring', 'Predictive Maintenance', 'AI-Driven Power Management', 'IoT Integration'],
          image: '/assets/images/engineers-inspecting-switchgear-panels-i.jpg',
        },
      ],
    },
  },
  {
    type: 'eco',
    section_key: 'eco',
    title: 'Ecosystem',
    content_json: {
      eyebrow: 'ONE ENGINEERING ECOSYSTEM',
      title: 'Zigma Technologies — Premium Power & Energy Solutions Company',
      body: 'A trusted engineering partner with over 20 years of expertise delivering comprehensive power, energy, and engineering solutions across manufacturing, healthcare, commercial, and institutional industries — from solar generation to power protection to the engineering design behind it all.',
      cta: 'Learn More About Zigma →',
      ctaHref: '#why',
      groups: [
        {
          className: 'cap-group-orange',
          items: ['UPS Sales & Services', 'UPS AMC Services', 'Battery & Energy Storage'],
          dot: 'dot-orange',
        },
        {
          className: 'cap-group-green',
          items: ['Solar EPC Solutions', 'Solar AMC & O&M Services', 'Solar Power Generation'],
          dot: 'dot-green',
        },
        {
          className: 'cap-group-blue',
          items: ['Industrial Power Solutions', 'Industrial & Power Electronics', 'Electrical Engineering'],
          dot: 'dot-blue',
        },
        {
          className: 'cap-group-purple',
          items: ['Energy Auditing & Optimization', 'Engineering Design & Outsourcing', 'Technical Consulting'],
          dot: 'dot-purple',
        },
      ],
    },
  },
  {
    type: 'stats',
    section_key: 'stats',
    title: 'Stat Bar',
    content_json: {
      stats: [
        { label: 'Years Experience', value: 20, suffix: '+' },
        { label: 'Projects Delivered', value: 1500, suffix: '+' },
        { label: 'Satisfied Clients', value: 1200, suffix: '+' },
        { label: 'Industries We Serve', value: 25, suffix: '+' },
        { label: 'Certified Engineers', value: 100, suffix: '+' },
        { label: 'Client Satisfaction', value: 99, suffix: '%+' },
      ],
    },
  },
  {
    type: 'why',
    section_key: 'why',
    title: 'Why Zigma',
    content_json: {
      eyebrow: 'WHY ZIGMA',
      title: 'One Partner. One Responsibility. Complete Power Solutions',
      body: 'Power infrastructure is more reliable when every system works as one. Zigma brings together Solar Energy, UPS Systems, Battery Storage, Engineering Excellence, AMC and 24×7 Service Support to deliver seamless, end-to-end power solutions.',
      cards: [
        { index: '01', title: '20-Year Engineering Bench', desc: "Teams who've solved this exact failure before, not first-time installers.", tint: 'tint-1' },
        { index: '02', title: 'One Partner Accountability', desc: 'Design, supply, install, and maintain — one contract, one escalation path.', tint: 'tint-2' },
        { index: '03', title: 'OEM-Aligned Delivery', desc: 'Authorized partnerships and certified processes for critical infrastructure.', tint: 'tint-3' },
        { index: '04', title: '24×7 Response Culture', desc: 'Mission-critical support when downtime is not an option.', tint: 'tint-4' },
        { index: '05', title: 'Built for Scale', desc: 'From a single rooftop system to multi-MW industrial EPC, without changing partners.', tint: 'tint-5' },
        { index: '06', title: 'Lifecycle Thinking', desc: 'CapEx decisions tied to OpEx reality — AMC, monitoring, and upgrade paths included.', tint: 'tint-6' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'generate',
    title: 'Generate Solar',
    content_json: {
      eyebrow: 'GENERATE',
      eyebrowClass: 'eyebrow-green',
      title: 'Solar Green Energy Solutions',
      body: 'Designing and delivering intelligent solar energy systems that maximize performance, efficiency, sustainability, and long-term return on investment for commercial, industrial, institutional, and utility-scale projects.',
      image: '/assets/images/aerial-view-of-dense-commercial-rooftop-.jpg',
      imagePosition: 'right',
      tone: 'ice',
      cta: 'Explore Solar Solutions →',
      ctaHref: '/contact',
      features: [
        { title: 'Solar EPC Engineering', body: 'Complete engineering, procurement, construction, and commissioning for rooftop, ground-mounted, and utility-scale solar power projects.', icon: '<path d="M3 21h18M5 21V9l6-4 6 4v12" /><path d="M9 21v-6h6v6" />' },
        { title: 'Solar Design & Detailed Engineering', body: 'Electrical design, system sizing, string layouts, load calculations, SLDs, and optimized solar plant engineering.', icon: '<path d="M3 3h18v18H3z" /><path d="M3 9h18M9 21V9" />' },
        { title: 'Energy Storage & Hybrid Systems', body: 'Advanced Battery Energy Storage Systems (BESS) and hybrid solar solutions for reliable backup, optimized energy usage, ensure uninterrupted backup, and maximum solar performance.', icon: '<rect x="5" y="9" width="14" height="10" rx="1.5" /><path d="M9 9V6a3 3 0 016 0v3" />' },
        { title: 'Solar AMC & O&M Support', body: 'Comprehensive AMC & O&M services that maximize energy generation, improve reliability, and keep your solar systems running efficiently, and protect your solar investment.', icon: '<circle cx="12" cy="12" r="8" /><path d="M12 8v4l3 2" />' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'protect',
    title: 'Protect Power',
    content_json: {
      eyebrow: 'PROTECT',
      eyebrowClass: 'eyebrow-orange',
      title: 'Power Continuity Solutions',
      body: 'Delivering reliable and uninterrupted power infrastructure through advanced UPS systems, battery solutions, critical power engineering, and electrical protection systems.',
      image: 'https://images.unsplash.com/photo-1695668548342-c0c1ad479aee?auto=format&fit=crop&w=1000&q=75',
      imagePosition: 'left',
      tone: 'light',
      cta: 'Protect Your Business →',
      ctaHref: '/contact',
      features: [
        { title: 'UPS Systems & Critical Power', body: 'Reliable online UPS solutions for mission-critical operations across commercial and industrial facilities.', icon: '<rect x="4" y="2" width="16" height="20" rx="2" /><path d="M9 7h6M9 11h6M9 15h3" />' },
        { title: 'Battery Backup Solutions', body: 'High-performance battery banks, energy storage, replacement, testing, and lifecycle management.', icon: '<rect x="5" y="9" width="14" height="10" rx="1.5" /><path d="M9 9V6a3 3 0 016 0v3" />' },
        { title: 'Electrical Distribution Systems', body: 'LV panels, switchgear, power distribution, protection coordination, and electrical infrastructure engineering.', icon: '<rect x="3" y="7" width="18" height="12" rx="1" /><path d="M7 7V5a2 2 0 012-2h6a2 2 0 012 2v2" />' },
        { title: 'Power Quality & Monitoring', body: 'Advanced monitoring, harmonic analysis, surge protection, power quality improvement, and preventive diagnostics.', icon: '<path d="M13 2L4 14h7l-1 8 9-12h-7z" />' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'bess',
    title: 'BESS',
    content_json: {
      eyebrow: 'BESS',
      eyebrowClass: 'eyebrow-orange',
      title: 'Battery Energy Storage Systems (BESS)',
      body: 'Intelligent energy storage for commercial, industrial, and utility-scale applications. We design, supply, install, integrate, and maintain advanced BESS that improve energy efficiency, reduce peak demand charges, provide reliable backup power, and maximize renewable energy utilization.',
      image: 'https://images.unsplash.com/photo-1589276534126-adef63a95e05?fm=jpg&q=80&w=1600&auto=format&fit=crop',
      imagePosition: 'right',
      tone: 'ice',
      cta: 'Request a BESS Consultation →',
      ctaHref: '/contact',
      features: [
        { title: 'Commercial & Industrial BESS', body: 'Turnkey battery storage sized for facility loads, backup requirements, and utility-scale deployments.', icon: '<rect x="2" y="8" width="18" height="8" rx="1.5"/><path d="M22 10v4"/><path d="M6 8v8M10 8v8"/>' },
        { title: 'Hybrid Solar + BESS Systems', body: 'Combined solar generation and storage for maximum renewable utilization and grid independence.', icon: '<path d="M12 2C7 6 4 9.5 4 13.5A8 8 0 0020 13.5C20 9.5 17 6 12 2z"/>' },
        { title: 'Peak Shaving & Load Management', body: 'Reduce peak demand charges and shift loads intelligently to cut energy costs.', icon: '<path d="M12 20V10M18 20V4M6 20v-4"/>' },
        { title: 'BMS, EMS & SCADA Integration', body: 'Battery Management Systems, Energy Management Systems, and remote SCADA monitoring built in.', icon: '<path d="M9 12l2 2 4-4"/><circle cx="12" cy="12" r="9"/>' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'maintain',
    title: 'Maintain',
    content_json: {
      eyebrow: 'MAINTAIN',
      eyebrowClass: 'eyebrow-cyan',
      title: 'Engineering Operations & Lifecycle Services',
      body: 'Comprehensive operation, maintenance, asset management, and engineering support services that ensure maximum system reliability and operational efficiency.',
      image: 'https://images.unsplash.com/photo-1758101755915-462eddc23f57?auto=format&fit=crop&w=1000&q=75',
      imagePosition: 'left',
      tone: 'light',
      cta: 'Discover Engineering Services →',
      ctaHref: '/contact',
      features: [
        { title: 'Operations & Maintenance (O&M)', body: 'Preventive and corrective maintenance for solar plants, electrical infrastructure, UPS systems, and industrial assets.', icon: '<path d="M9 12l2 2 4-4" /><circle cx="12" cy="12" r="9" />' },
        { title: 'Annual Maintenance Contracts (AMC)', body: 'Flexible AMC programs providing scheduled inspections, maintenance, and priority technical support.', icon: '<rect x="3" y="4" width="18" height="16" rx="2" /><path d="M3 9h18M8 4v5" />' },
        { title: 'Remote Monitoring & Diagnostics', body: '24×7 system monitoring, predictive maintenance, fault detection, and performance reporting.', icon: '<circle cx="12" cy="12" r="3" /><path d="M12 2v3M12 19v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2 12h3M19 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1" />' },
        { title: 'Engineering Support Services', body: 'Technical audits, troubleshooting, modernization, retrofits, documentation, and lifecycle engineering support.', icon: '<path d="M14.7 6.3a4 4 0 01-5.6 5.6L4 17l3 3 5.1-5.1a4 4 0 015.6-5.6z" />' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'ev-charging',
    title: 'EV Charging',
    content_json: {
      eyebrow: 'EV CHARGING',
      eyebrowClass: 'eyebrow-orange',
      title: 'EV Charging Infrastructure',
      body: "Empowering India's transition to electric mobility with reliable, scalable, and intelligent EV charging solutions. We handle end-to-end design, supply, installation, commissioning, and AMC for AC & DC charging infrastructure — integrated seamlessly with solar and Battery Energy Storage Systems (BESS).",
      image: '/assets/images/blue-electric-vehicle-charging-at-a-mode.jpg',
      imagePosition: 'right',
      tone: 'ice',
      cta: 'Get an EV Charging Proposal →',
      ctaHref: '/contact',
      features: [
        { title: 'AC & DC Charging Stations', body: 'Fast and slow charging infrastructure engineered for commercial, industrial, fleet, and public deployment.', icon: '<path d="M13 2L4 14h7l-1 8 9-12h-7l1-8z"/>' },
        { title: 'Commercial & Fleet Charging', body: 'Corporate campuses, apartments, highway stations, and dedicated fleet charging depots.', icon: '<path d="M3 21h18M5 21V9l6-4 6 4v12M9 21v-6h6v6"/>' },
        { title: 'Solar + EV + BESS Integration', body: 'Charging networks that draw from solar generation and battery storage for lower running costs.', icon: '<path d="M12 2C7 6 4 9.5 4 13.5A8 8 0 0020 13.5C20 9.5 17 6 12 2z"/>' },
        { title: 'Smart OCPP Charging & AMC', body: 'OCPP-based load management, remote monitoring, charger repair, and annual maintenance contracts.', icon: '<path d="M5 12a7 7 0 0114 0M2 12a10 10 0 0120 0"/><circle cx="12" cy="12" r="1.4" fill="currentColor" stroke="none"/>' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'engineering-design',
    title: 'Engineering Design',
    content_json: {
      eyebrow: 'ENGINEERING',
      eyebrowClass: 'eyebrow-orange',
      title: 'Engineering Design & Development',
      body: "From concept to commissioning — our engineering bench designs, models, and validates every system before it's ever installed on-site.",
      image: '/assets/images/engineers-in-hard-hats-reviewing-a-digit.jpg',
      imagePosition: 'left',
      tone: 'light',
      cta: 'Discuss Your Engineering Project →',
      ctaHref: '/contact',
      features: [
        { title: 'Electrical Design & Detailed Engineering', body: 'Single-line diagrams, load calculations, and detailed electrical design engineered for your exact site conditions.', icon: '<path d="M3 3h18v18H3z"/><path d="M3 9h18M9 21V9"/>' },
        { title: 'Prototyping & Product Development', body: 'Rapid prototyping and iterative development to prove out new power system designs before scale-up.', icon: '<path d="M12 2l3 6 6 1-4.5 4.5L18 20l-6-3-6 3 1.5-6.5L3 9l6-1z"/>' },
        { title: 'Technical Drawings & Documentation', body: 'CAD layouts, schematics, and as-built documentation delivered to a standard your team can act on.', icon: '<path d="M4 4h16v16H4z"/><path d="M8 4v16M4 9h4M4 15h4"/>' },
        { title: 'Testing, Commissioning & Validation', body: 'Factory and site acceptance testing, commissioning, and performance validation before handover.', icon: '<path d="M9 12l2 2 4-4"/><circle cx="12" cy="12" r="9"/>' },
      ],
    },
  },
  {
    type: 'split',
    section_key: 'experts',
    title: 'Experts',
    content_json: {
      eyebrow: 'EXPERTISE',
      eyebrowClass: 'eyebrow-cyan',
      title: 'Experts in Industrial & Power Electronics',
      body: 'Deep engineering expertise in rectifiers, converters, drives, and industrial power electronics — the foundational layer behind every protection system we build.',
      image: 'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?auto=format&fit=crop&w=1000&q=75',
      imagePosition: 'right',
      tone: 'ice',
      cta: 'Talk to Our Power Electronics Team →',
      ctaHref: '/contact',
      features: [
        { title: 'Rectifiers & Converters', body: 'Precision-engineered AC-DC and DC-DC conversion systems built for demanding industrial duty cycles.', icon: '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 2v3M16 2v3M8 19v3M16 19v3M2 8h3M2 16h3M19 8h3M19 16h3"/>' },
        { title: 'Drives & Motor Control', body: 'Variable frequency drives and motor control systems tuned for efficiency and reliability at scale.', icon: '<circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/>' },
        { title: 'Power Electronics Consulting', body: 'Design reviews, failure analysis, and specification support from engineers who build this equipment.', icon: '<path d="M13 2L4 14h7l-1 8 9-12h-7z"/>' },
        { title: 'Inverter Installation & Service', body: 'On-site inverter installation, commissioning, repair, and service support across major solar and industrial brands.', icon: '<rect x="3" y="7" width="18" height="12" rx="1"/><path d="M7 7V5a2 2 0 012-2h6a2 2 0 012 2v2"/>' },
      ],
    },
  },
  {
    type: 'timeline',
    section_key: 'legacy',
    title: 'Legacy Timeline',
    content_json: {
      eyebrow: '20-YEARS OF LEGACY',
      title: "Twenty years isn't a number. It's a track record.",
      items: [
        { year: '2006', title: 'Founded', body: 'Zigma Technologies founded, focused on industrial electrical and power backup services.' },
        { year: '2010+', title: 'UPS & AMC Expansion', body: 'Expansion into UPS sales, service, and structured Annual Maintenance Contracts across manufacturing clients.' },
        { year: '2015+', title: 'Solar Division', body: 'Entry into Solar EPC as renewable energy adoption accelerates among Indian industry.' },
        { year: '2020+', title: 'Full Power Lifecycle', body: 'Battery solutions, power quality, and energy management added — completing the integrated offering.' },
        { year: 'Today', title: '1,000+ Projects', body: 'Pan-India service footprint and a new phase of expansion into large-scale industrial solar.', now: true },
        { year: "What's Next", title: 'Future Vision', body: "Scaling engineering capacity to serve India's next decade of industrial energy demand.", next: true },
      ],
      cta: 'Read Our Full Story →',
      ctaHref: '/#legacy',
    },
  },
  {
    type: 'projects_teaser',
    section_key: 'projects',
    title: 'Featured Case Studies',
    content_json: {
      eyebrow: 'PROOF, NOT PROMISES',
      title: 'Featured case studies',
      source: 'case_studies',
      limit: 3,
      cta: 'View All Case Studies →',
      ctaHref: '/projects',
    },
  },
  {
    type: 'industries',
    section_key: 'industries',
    title: 'Industries',
    content_json: {
      eyebrow: 'INDUSTRIES',
      title: 'Engineering that understands your industry.',
      linkLabel: 'See All Industries We Serve →',
      linkHref: '/industries',
      items: [
        'Data Centers & IT Parks',
        'Digital Infrastructure',
        'Government & Public Sector',
        'Manufacturing',
        'Automotive Industry',
        'Airport & Metro Infrastructure',
        'Industrial Infrastructure',
        'Hospitality & Hotels',
        'MSMEs & Small-Scale Industries',
        'Telecom & Communication',
        'Smart Cities & Utilities',
        'Special Economic Zones (SEZ)',
        'Warehouse, Logistics & Fleet Operators',
        'Power & Utility Infrastructure',
        'Oil & Gas Refineries',
        'Healthcare & Hospitals',
        'Educational Institutions',
        'Residential Communities',
        'Commercial Real Estate',
        'Corporate Campuses',
        'Banking & Financial Services',
        'Engineering, Procurement & Construction (EPC)',
        'EV Charging Infrastructure',
        'Renewable Energy Developers',
      ],
    },
  },
  {
    type: 'testimonials',
    section_key: 'testimonials',
    title: 'Testimonials',
    content_json: {
      eyebrow: 'TESTIMONIALS',
      title: "Trusted by the people who can't afford downtime.",
      items: [
        {
          quote:
            "When our UPS failed at 2 AM, Zigma's engineer was on-site before our own maintenance team could even respond. That's twenty years of reliability, not luck.",
          name: 'RAJESH IYER',
          role: 'Plant Head, Precision Auto Components',
        },
        {
          quote:
            "They didn't just install our rooftop solar system — they sat with our facilities team and rebuilt our entire load management approach.",
          name: 'DR. ANITA MENON',
          role: 'Facility Director, Sunrise Multi-Specialty Hospital',
        },
        {
          quote:
            'We evaluated four EPC vendors. Zigma was the only one that came back with load calculations instead of a quotation.',
          name: 'VIKRAM SHARMA',
          role: 'Operations Head, Meridian Textiles',
        },
      ],
    },
  },
  {
    type: 'partners',
    section_key: 'partners',
    title: 'Partners',
    content_json: {
      eyebrow: 'SOURCED & SERVICED',
      title: 'Trusted by industry leaders and engineering partners.',
      note: 'Logos represent equipment and technology brands Zigma sources and services, and organizations Zigma has partnered with or delivered projects for. All logos remain the property of their respective owners and are displayed as provided.',
      logos: [
        { src: '/assets/images/abb.png', alt: 'ABB' },
        { src: '/assets/images/abb-2.png', alt: 'ABB Partner' },
        { src: '/assets/images/aditya-birla-group.png', alt: 'Aditya Birla Group' },
        { src: '/assets/images/amara-raja.png', alt: 'Amara Raja' },
        { src: '/assets/images/aster-hospital.png', alt: 'Aster Hospital' },
        { src: '/assets/images/bharat-electronics.png', alt: 'Bharat Electronics' },
        { src: '/assets/images/bangalore-international-exhibition-centr.png', alt: 'BIEC' },
        { src: '/assets/images/coca-cola.png', alt: 'Coca-Cola' },
        { src: '/assets/images/eaton.png', alt: 'Eaton' },
        { src: '/assets/images/emudhra.png', alt: 'eMudhra' },
        { src: '/assets/images/exide.png', alt: 'Exide' },
        { src: '/assets/images/fincare-small-finance-bank.png', alt: 'Fincare' },
        { src: '/assets/images/hitachi.png', alt: 'Hitachi' },
        { src: '/assets/images/indigo.png', alt: 'IndiGo' },
        { src: '/assets/images/jana-small-finance-bank.png', alt: 'Jana Bank' },
        { src: '/assets/images/kempegowda-international-airport-bengalu.png', alt: 'KIA Bengaluru' },
        { src: '/assets/images/kirloskar-solar.png', alt: 'Kirloskar Solar' },
        { src: '/assets/images/kotak-mahindra-bank.png', alt: 'Kotak Mahindra Bank' },
        { src: '/assets/images/landmark-group.png', alt: 'Landmark Group' },
        { src: '/assets/images/leoch-battery.png', alt: 'Leoch Battery' },
        { src: '/assets/images/lifestyle.png', alt: 'Lifestyle' },
        { src: '/assets/images/luminous.png', alt: 'Luminous' },
        { src: '/assets/images/max.png', alt: 'Max' },
        { src: '/assets/images/numeric.png', alt: 'Numeric' },
        { src: '/assets/images/schneider-electric.png', alt: 'Schneider Electric' },
        { src: '/assets/images/shadowfax.png', alt: 'Shadowfax' },
        { src: '/assets/images/somerset-therapeutics.png', alt: 'Somerset Therapeutics' },
        { src: '/assets/images/tke.png', alt: 'TKE' },
        { src: '/assets/images/vertiv.png', alt: 'Vertiv' },
        { src: '/assets/images/vi.png', alt: 'Vi' },
      ],
    },
  },
  {
    type: 'cert_teaser',
    section_key: 'cert-teaser',
    title: 'Certifications Teaser',
    content_json: {
      eyebrow: 'CERTIFICATIONS',
      title: 'Certified Excellence. Trusted Performance.',
      body: 'OEM authorizations, ISO certification, and engineering partnerships that back every project we deliver.',
      cta: 'View Our Certifications →',
      ctaHref: '/certifications',
    },
  },
  {
    type: 'cta',
    section_key: 'contact',
    title: 'Contact CTA',
    content_json: {
      title: "Let's build India's next 20 years of reliable power.",
      body: "Whether it's a single rooftop system or a multi-site industrial rollout, our engineers will size it right the first time.",
      primaryCta: 'Talk to an Engineer',
      primaryHref: 'tel:+919590137444',
      secondaryCta: 'Contact Us',
      secondaryHref: '/contact',
    },
  },
] as const;

export const DEFAULT_THEME_TOKENS = {
  '--navy-950': '#0A1628',
  '--navy-900': '#0F1F3D',
  '--orange': '#FF6B1A',
  '--orange-dim': '#c9540f',
  '--green': '#12B76A',
  '--cyan': '#00D4FF',
  '--graphite-800': '#1E2530',
  '--graphite-500': '#5B6472',
  '--section-pad': '9rem',
};
