-- SEO Phase 3: hand-written meta titles, descriptions and image alt text (see SEO-GUIDE.md, Phase 3).
-- Titles are written without the brand; " | Zigma Technologies" is appended by the site.
-- Safe to re-run. Run with: mysql --default-character-set=utf8mb4 -u USER -p DB < scripts/seo-phase3-content.sql
SET NAMES utf8mb4;
START TRANSACTION;

-- CMS pages (Admin → Pages → Sections → Page details / SEO)
UPDATE pages SET meta_title = 'Solar EPC, UPS, BESS & EV Charging Company in India', meta_description = 'Power and energy engineering for factories, hospitals and campuses since 2006. Solar EPC, UPS, battery storage, EV charging and 24×7 AMC. Get a quote.' WHERE slug = 'home';
UPDATE pages SET meta_title = 'Contact Us – Solar, UPS, BESS & EV Charging Enquiries', meta_description = 'Talk to our engineers about solar EPC, UPS, BESS, EV charging or AMC. Bengaluru head office, pan-India service hubs, reply within one business day.' WHERE slug = 'contact';
UPDATE pages SET meta_title = 'Careers in Solar, UPS & Power Engineering – Bengaluru', meta_description = 'Join 150+ engineers building solar, UPS and battery systems across India. Open roles in Bengaluru, Mumbai and Delhi, plus paid internships. Apply online.' WHERE slug = 'careers';
UPDATE pages SET meta_title = 'Certifications – ABB, Schneider, Kirloskar & ISO 9001', meta_description = 'ABB channel partner, Schneider Electric and Kirloskar Solar authorised, ISO 9001:2015 certified, recognised at the Karnataka Solar Awards 2025. View proof.' WHERE slug = 'certifications';
UPDATE pages SET meta_title = 'Privacy Policy', meta_description = 'How Zigma Technologies collects, uses, stores and protects the personal information you share through our website, enquiry forms and job applications.' WHERE slug = 'privacy';
UPDATE pages SET meta_title = 'Terms of Use', meta_description = 'The terms that govern your use of the Zigma Technologies website, including its content, enquiry forms, intellectual property and limits of liability.' WHERE slug = 'terms';

-- Projects, products, services (Admin → Inventory → Edit → SEO)
UPDATE catalog_items SET meta_title = 'UPS AMC Across India – 1 to 500 kVA, All Major Brands', meta_description = 'Post-warranty UPS maintenance with preventive visits, battery testing, load tests and emergency call-outs. 10,000+ AMCs done in 500+ cities. Get a quote.' WHERE item_type = 'service' AND slug = 'ups-amc';
UPDATE catalog_items SET meta_title = 'UPS Repair Service – Onsite & Workshop, Out of Warranty', meta_description = 'Failed or ageing UPS? Our engineers diagnose faults, repair on site or in our workshop, and check battery health to get you back online fast. Book a visit.' WHERE item_type = 'service' AND slug = 'ups-repair-service';
UPDATE catalog_items SET meta_title = 'UPS Rental for Events, Exams & Temporary Power Needs', meta_description = 'Rent a UPS for hours, days or months. Delivery, installation, battery backup, on-site monitoring and pickup included, with no capital cost. Get a quote.' WHERE item_type = 'service' AND slug = 'ups-rental';
UPDATE catalog_items SET meta_title = 'Solar O&M Services – Cleaning, Inspection & Repairs', meta_description = 'Keep your rooftop or ground-mount solar plant at peak yield with scheduled cleaning, inverter health checks, fault repairs and safety checks. Get a plan.' WHERE item_type = 'service' AND slug = 'solar-maintenance-service';
UPDATE catalog_items SET meta_title = 'UPS & Solar Installation and Commissioning Services', meta_description = 'Site survey, design, cabling, testing and commissioning for UPS systems and solar plants, done by our own field crews with full handover documents.' WHERE item_type = 'service' AND slug = 'field-installation-commissioning';
UPDATE catalog_items SET meta_title = 'Electrical Design Outsourcing – EPLAN & AutoCAD Drawings', meta_description = 'Outsource panel, SLD and plant electrical drawings to our EPLAN and AutoCAD engineers. QA-checked, confidential and scaled to your project peaks.' WHERE item_type = 'service' AND slug = 'design-outsource-support';
UPDATE catalog_items SET meta_title = 'Studer Hybrid Inverter + Lithium Battery for Petroleum Site', meta_description = 'How we designed and commissioned a Studer hybrid power system with lithium storage and remote monitoring to keep a petroleum site''s critical loads running.' WHERE item_type = 'project' AND slug = 'studer-hybrid-lithium-petroleum-project';
UPDATE catalog_items SET meta_title = '200 kW Rooftop Solar for AMC Engineering College, Bengaluru', meta_description = 'A 200 kW rooftop solar EPC project for AMC Engineering College, sequenced around campus activity to cut daytime grid use. See the scope and results.' WHERE item_type = 'project' AND slug = 'amc-engineering-college-200kw-bangalore';
UPDATE catalog_items SET meta_title = '600 kW Industrial Solar Plant for Agro-Food Factory, Tumkur', meta_description = 'How we engineered and commissioned a 600 kW solar plant for Sri Rajalakshimi Agro Foods, sized to its daytime process load. Scope, equipment and results.' WHERE item_type = 'project' AND slug = 'sri-rajalakshimi-agro-foods-600kw-tumkur';
UPDATE catalog_items SET meta_title = '200 kW Solar Plant for Rice Processing Mill, Tumkur', meta_description = '200 kW solar EPC for Karnataka Rice Industries, matched to the mill''s operating hours to cut daytime grid spend. See the scope, equipment and outcomes.' WHERE item_type = 'project' AND slug = 'karnataka-rice-industries-200kw-tumkur';
UPDATE catalog_items SET meta_title = '200 kW Rooftop Solar for Eshwari Agro Foods Plant, Tumkur', meta_description = 'Design, installation and commissioning of a 200 kW rooftop solar system that offsets Eshwari Agro Foods'' rising daytime power costs. Read the case study.' WHERE item_type = 'project' AND slug = 'eshwari-agro-foods-200kw-tumkur';
UPDATE catalog_items SET meta_title = '149 kW Rooftop Solar for Stone Processing Unit, Tumkur', meta_description = 'A 149 kW rooftop solar plant for Shiva Stones, sized to the roof area and daytime production load to reduce energy costs. Read the project details.' WHERE item_type = 'project' AND slug = 'shiva-stones-149kw-tumkur';
UPDATE catalog_items SET meta_title = '55 kW Rooftop Solar for Mysore Drier Tech Factory, Tumkur', meta_description = 'A right-sized 55 kW rooftop solar system for Mysore Drier Tech''s drying operations, delivered without oversizing capital cost. See scope and outcomes.' WHERE item_type = 'project' AND slug = 'mysore-drier-tech-55kw-tumkur';
UPDATE catalog_items SET meta_title = 'ABB UPS Installation, 2 × 160 kVA Redundant – Bengaluru', meta_description = 'Installation and commissioning of two ABB 160 kVA UPS units in a redundant setup, with battery banks, to protect critical loads at a Bengaluru site.' WHERE item_type = 'project' AND slug = 'abb-ups-installation-bangalore-320kw';
UPDATE catalog_items SET meta_title = '90 kVA Data Centre UPS Installation for eMudhra, Chennai', meta_description = 'Supply, battery integration and commissioning of a 90 kVA UPS in eMudhra''s live Chennai data centre to protect critical IT services. Read the case study.' WHERE item_type = 'project' AND slug = 'emudra-data-centre-ups-chennai-90kva';
UPDATE catalog_items SET meta_title = 'ABB Industrial & Server UPS – Supply, Install & AMC', meta_description = 'ABB UPS systems for factories, process control and server rooms, supplied and commissioned by an authorised ABB channel partner. Ask for a quote.' WHERE item_type = 'product' AND slug = 'abb-industrial-server-ups';
UPDATE catalog_items SET meta_title = 'APC Schneider UPS – Home, IT & Industrial Backup Power', meta_description = 'APC by Schneider Electric UPS for offices, IT racks and industrial loads. Authorised partner for sizing, installation, batteries and AMC. Get a price.' WHERE item_type = 'product' AND slug = 'apc-schneider-ups-systems';
UPDATE catalog_items SET meta_title = 'Vertiv UPS Systems for Data Centres & Critical Facilities', meta_description = 'Vertiv online UPS platforms for data centres, hospitals and critical facilities, with site sizing, installation, battery banks and AMC. Request a quote.' WHERE item_type = 'product' AND slug = 'vertiv-ups-systems';
UPDATE catalog_items SET meta_title = 'Numeric UPS Systems – Online UPS for Offices & Factories', meta_description = 'Numeric online UPS for offices, retail and factories. We size the system, supply batteries, install, commission and maintain it under AMC. Get a quote.' WHERE item_type = 'product' AND slug = 'numeric-ups-systems';
UPDATE catalog_items SET meta_title = 'Eaton UPS Systems – Enterprise & Industrial Power Protection', meta_description = 'Eaton UPS for enterprise IT, data centres and industrial plants, from single units to large three-phase systems. Supply, installation and AMC. Get a quote.' WHERE item_type = 'product' AND slug = 'eaton-ups-systems';
UPDATE catalog_items SET meta_title = 'Delta UPS Systems – Online UPS for IT Rooms & Industry', meta_description = 'Delta online UPS platforms for server rooms, labs and industrial lines, with sizing, battery banks, installation and 24×7 AMC support. Ask for a price.' WHERE item_type = 'product' AND slug = 'delta-ups-systems';
UPDATE catalog_items SET meta_title = 'Powerone UPS Systems – Commercial & Industrial Backup Power', meta_description = 'Powerone UPS systems for commercial buildings and industrial plants, supplied with batteries, installed, commissioned and serviced by our engineers.' WHERE item_type = 'product' AND slug = 'powerone-ups-systems';
UPDATE catalog_items SET meta_title = 'Studer XTM Hybrid Inverter/Charger – Modular Off-Grid', meta_description = 'Swiss-made Studer Xtender XTM inverter/charger for scalable off-grid and hybrid systems. Parallel-ready, solar and battery ready, installed by our team.' WHERE item_type = 'product' AND slug = 'studer-xtm-series';
UPDATE catalog_items SET meta_title = 'Studer XTH Hybrid Inverter/Charger – High-Performance Backup', meta_description = 'Studer Xtender XTH hybrid inverter/charger for demanding off-grid, hybrid and backup sites where heavy loads and reliability matter. Get sizing help.' WHERE item_type = 'product' AND slug = 'studer-xth-series';
UPDATE catalog_items SET meta_title = 'Studer XTS Compact Hybrid Inverter/Charger – Rugged Build', meta_description = 'Compact Studer Xtender XTS inverter/charger for small hybrid and off-grid installations where space is tight. Supply, wiring and commissioning available.' WHERE item_type = 'product' AND slug = 'studer-xts-series';
UPDATE catalog_items SET meta_title = 'Kirloskar Solar Panels – Rooftop & Plant-Scale Modules', meta_description = 'Kirloskar Solar modules for homes, commercial rooftops and industrial plants, supplied and installed by an authorised Kirloskar Solar partner. Get a quote.' WHERE item_type = 'product' AND slug = 'kirloskar-solar-modules';
UPDATE catalog_items SET meta_title = 'On-Grid String Solar Inverters for Commercial Rooftops', meta_description = 'Grid-tied string inverters for commercial and industrial solar plants, matched to your array and export limits, with installation and O&M support.' WHERE item_type = 'product' AND slug = 'on-grid-string-solar-inverters';
UPDATE catalog_items SET meta_title = 'Off-Grid Solar Inverters for Battery-Backed & Remote Sites', meta_description = 'Off-grid solar inverters for sites with no or unreliable grid supply. Sized with batteries and panels, then installed and commissioned by our engineers.' WHERE item_type = 'product' AND slug = 'off-grid-solar-inverters';
UPDATE catalog_items SET meta_title = 'Solar Combo Kits – Panels, Inverter & Battery Packages', meta_description = 'Ready solar packages with panels, inverter and batteries in on-grid or off-grid form, sized to your load and roof. Supply and installation available.' WHERE item_type = 'product' AND slug = 'on-off-grid-solar-combos';
UPDATE catalog_items SET meta_title = 'Microtek Inverters for Home, Office & Solar Backup', meta_description = 'Microtek home and office inverters, including solar-hybrid models, supplied with matching batteries and installed by our technicians. Ask for a price.' WHERE item_type = 'product' AND slug = 'microtek-inverters';
UPDATE catalog_items SET meta_title = 'Luminous Inverters for Homes, Shops & Industrial Backup', meta_description = 'Luminous inverters for homes, shops, offices and light industrial loads, paired with the right battery and installed by our service team. Get a quote.' WHERE item_type = 'product' AND slug = 'luminous-inverters';
UPDATE catalog_items SET meta_title = 'Eastman Inverters for Reliable Home & Solar-Ready Backup', meta_description = 'Eastman inverters for homes and small businesses, compatible with solar charging and supplied with matching batteries, installation and service support.' WHERE item_type = 'product' AND slug = 'eastman-inverters';
UPDATE catalog_items SET meta_title = 'Amaron Quanta VRLA Batteries for UPS, Inverter & Telecom', meta_description = 'Sealed, maintenance-free Amaron Quanta VRLA batteries for UPS, inverter and telecom backup. Correct sizing, installation and battery health checks.' WHERE item_type = 'product' AND slug = 'amaron-quanta-batteries';
UPDATE catalog_items SET meta_title = 'Exide Batteries – Inverter, UPS & Solar Deep-Cycle Range', meta_description = 'Exide tubular, VRLA and deep-cycle batteries for inverters, UPS and solar systems, supplied, installed and tested by our engineers. Ask for a price.' WHERE item_type = 'product' AND slug = 'exide-batteries';
UPDATE catalog_items SET meta_title = 'Eastman Tubular Batteries for Inverter & UPS Backup', meta_description = 'Eastman tubular batteries for home inverters and UPS systems in multiple capacities, with correct sizing and professional installation. Get a quote.' WHERE item_type = 'product' AND slug = 'eastman-batteries';
UPDATE catalog_items SET meta_title = 'Static Voltage Regulator – ±1% Regulation, IGBT (Optimus)', meta_description = 'Zigma Optimus static voltage regulators with PWM/IGBT control, ±1% output regulation and correction within 20 ms. Protect sensitive machines. Get a quote.' WHERE item_type = 'product' AND slug = 'zigma-static-voltage-regulators';
UPDATE catalog_items SET meta_title = 'APC Battery Management System – UPS Battery Monitoring', meta_description = 'APC battery management modules, sensors and harnesses that track UPS battery health and flag weak batteries before they fail during a power cut.' WHERE item_type = 'product' AND slug = 'apc-battery-management-system';
UPDATE catalog_items SET meta_title = 'Utility-Scale Battery Energy Storage (BESS) – Containerised', meta_description = 'Containerised battery energy storage for peak shaving, backup and solar firming at plants and utilities, with EMS integration and commissioning.' WHERE item_type = 'product' AND slug = 'utility-scale-bess';
UPDATE catalog_items SET meta_title = 'Peak Shaving BESS with Energy Management System (EMS)', meta_description = 'Battery storage plus EMS that cuts maximum-demand charges and automates energy dispatch between grid, solar and storage. Request a feasibility study.' WHERE item_type = 'product' AND slug = 'peak-shaving-ems-bess';
UPDATE catalog_items SET meta_title = 'EV Charging Infrastructure – AC & DC Chargers for Businesses', meta_description = 'AC and DC EV charging stations for campuses, fleets and commercial sites, with site survey, power planning, installation and maintenance. Get a quote.' WHERE item_type = 'product' AND slug = 'ev-charging-infrastructure';
UPDATE catalog_items SET meta_title = 'Smart EV Charging – Load Management for Fleets & Campuses', meta_description = 'Networked EV chargers with load management, usage monitoring and fleet controls, so more vehicles charge without overloading your supply. Talk to us.' WHERE item_type = 'product' AND slug = 'smart-ev-charging-solutions';
UPDATE catalog_items SET meta_title = 'Solar + Battery Storage + EV Charging, Integrated System', meta_description = 'Combine rooftop solar, battery storage and EV chargers in one system to charge vehicles on clean power and lower energy costs. Get a design proposal.' WHERE item_type = 'product' AND slug = 'solar-bess-ev-charging';

-- Resource articles (Admin → Resources)
UPDATE resource_posts SET meta_title = 'How to Size a UPS: kVA, Backup Time & Redundancy Guide', meta_description = 'Size a UPS right: convert kW to kVA, add growth headroom, choose backup time and N or N+1 redundancy. A practical checklist for server rooms and plants.' WHERE slug = 'ups-sizing-guide';
UPDATE resource_posts SET meta_title = 'Commercial Rooftop Solar O&M Checklist: Monthly & Quarterly', meta_description = 'Monthly and quarterly O&M tasks that protect rooftop solar yield and warranty: string checks, inverter alarms, thermal imaging, IV curves and earthing.' WHERE slug = 'solar-om-checklist';
UPDATE resource_posts SET meta_title = 'BESS Peak Shaving: When Battery Storage Pays for Itself', meta_description = 'How battery storage with an EMS cuts demand-charge spikes, which sites benefit most (factories, campuses, solar plants) and how to plan a BESS that pays.' WHERE slug = 'bess-peak-shaving';

-- Industry pages: clear the old seeded "<Name> | Zigma Technologies" titles so Admin → Site Copy → SEO applies.
-- Rows with hand-typed SEO text are left alone.
UPDATE pages SET meta_title = NULL, meta_description = NULL WHERE slug = 'industries' AND meta_title = 'Industries | Zigma Technologies';
UPDATE pages SET meta_title = NULL, meta_description = NULL WHERE slug LIKE 'industries-%' AND meta_title LIKE '% | Zigma Technologies';

-- Catalog gallery image alt text (shown on project / product / service pages; local and production image paths)
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Technician in a hard hat checking a rooftop solar panel during installation' WHERE c.slug = 'field-installation-commissioning' AND m.url IN ('/assets/images/seed-service-field.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'APC Back-UPS unit, one of the UPS brands covered under our AMC' WHERE c.slug = 'ups-amc' AND m.url IN ('/assets/images/seed-service-ups-amc.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Engineer inspecting cabling in a server rack during a UPS fault check' WHERE c.slug = 'ups-repair-service' AND m.url IN ('/assets/images/seed-service-ups-repair.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Range of tower and cabinet online UPS units available for short-term rental' WHERE c.slug = 'ups-rental' AND m.url IN ('/assets/images/seed-service-ups-rental.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Two technicians inspecting solar panels on a pitched roof during maintenance' WHERE c.slug = 'solar-maintenance-service' AND m.url IN ('/assets/images/seed-service-solar-om.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Orange industrial robots on an automated factory assembly line' WHERE c.slug = 'design-outsource-support' AND m.url IN ('/assets/images/seed-service-design.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Studer Xtender hybrid inverters and lithium battery control panels built for a petroleum site' WHERE c.slug = 'studer-hybrid-lithium-petroleum-project' AND m.url IN ('/assets/images/seed-project-petroleum.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Aerial view of AMC Engineering College, Bengaluru, with rooftop solar panels' WHERE c.slug = 'amc-engineering-college-200kw-bangalore' AND m.url IN ('/assets/images/seed-project-amc-college.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Technicians on the 600 kW rooftop solar array at Sri Rajalakshimi Agro Foods, Tumkur' WHERE c.slug = 'sri-rajalakshimi-agro-foods-600kw-tumkur' AND m.url IN ('/assets/images/seed-project-rajalakshimi.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Aerial view of 200 kW rooftop solar panels on the Karnataka Rice Industries mill, Tumkur' WHERE c.slug = 'karnataka-rice-industries-200kw-tumkur' AND m.url IN ('/assets/images/seed-project-karnataka-rice.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Drone view of the 200 kW rooftop solar array on Eshwari Agro Foods factory, Tumkur' WHERE c.slug = 'eshwari-agro-foods-200kw-tumkur' AND m.url IN ('/assets/images/seed-project-eshwari.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = '149 kW rooftop solar panels on the Shiva Stones factory shed in Tumkur' WHERE c.slug = 'shiva-stones-149kw-tumkur' AND m.url IN ('/assets/images/seed-project-shiva-stones.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = '55 kW solar panels on the red metal roof of Mysore Drier Tech, Tumkur' WHERE c.slug = 'mysore-drier-tech-55kw-tumkur' AND m.url IN ('/assets/images/seed-project-mysore-drier.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'ABB engineer commissioning UPS cabinets beside battery racks at a Bengaluru site' WHERE c.slug = 'abb-ups-installation-bangalore-320kw' AND m.url IN ('/assets/images/seed-project-abb-ups.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = '90 kVA UPS, battery racks and power distribution panel in eMudhra''s Chennai data centre' WHERE c.slug = 'emudra-data-centre-ups-chennai-90kva' AND m.url IN ('/assets/images/seed-project-emudra.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'ABB PowerValue online tower UPS with LCD status display' WHERE c.slug = 'abb-industrial-server-ups' AND m.url IN ('/assets/images/1789031652755-eh4bzb.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'APC Back-UPS Pro 700, 1000 and 1500 tower UPS units' WHERE c.slug = 'apc-schneider-ups-systems' AND m.url IN ('/assets/images/seed-apc-ups.jpg', '/assets/images/1789737371916-t9z0eh.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Vertiv Liebert floor-standing online UPS cabinet with touchscreen display' WHERE c.slug = 'vertiv-ups-systems' AND m.url IN ('/assets/images/seed-vertiv-ups.jpg', '/assets/images/1789737477779-hize97.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Numeric online UPS systems for commercial and industrial backup power' WHERE c.slug = 'numeric-ups-systems' AND m.url IN ('/assets/images/seed-numeric-ups.jpg', '/assets/images/1789737514668-3uq7jp.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Eaton high-capacity three-phase UPS cabinet for data centres' WHERE c.slug = 'eaton-ups-systems' AND m.url IN ('/assets/images/seed-eaton-ups.jpg', '/assets/images/1789739199210-df9wes.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Delta UPS range from compact tower units to modular rack cabinets' WHERE c.slug = 'delta-ups-systems' AND m.url IN ('/assets/images/seed-delta-ups.jpg', '/assets/images/1789739544518-20j865.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Powerone three-phase online UPS cabinets in three power ratings' WHERE c.slug = 'powerone-ups-systems' AND m.url IN ('/assets/images/seed-powerone-ups.jpg', '/assets/images/1789738944653-vq0yui.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Studer Xtender XTM 2600-48 hybrid inverter/charger, front view' WHERE c.slug = 'studer-xtm-series' AND m.url IN ('/assets/images/seed-studer-xtm.jpg', '/assets/images/1789740259580-38q84z.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Studer Xtender XTH hybrid inverter/charger in a grey enclosure' WHERE c.slug = 'studer-xth-series' AND m.url IN ('/assets/images/seed-studer-xth.jpg', '/assets/images/1789740342301-6ajtqk.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Compact Studer Xtender XTS inverter/charger in a finned aluminium case' WHERE c.slug = 'studer-xts-series' AND m.url IN ('/assets/images/seed-studer-xts.jpg', '/assets/images/1789740373707-5j2c4v.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Kirloskar Solar range of mono and polycrystalline solar panels' WHERE c.slug = 'kirloskar-solar-modules' AND m.url IN ('/assets/images/seed-solar-modules.jpg', '/assets/images/1789740794371-sqv7ed.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Kirloskar Solar on-grid string inverter for rooftop plants' WHERE c.slug = 'on-grid-string-solar-inverters' AND m.url IN ('/assets/images/seed-ongrid-inverter.jpg', '/assets/images/1789740813866-8wxbza.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Wall-mounted Kirloskar Solar off-grid PV inverter' WHERE c.slug = 'off-grid-solar-inverters' AND m.url IN ('/assets/images/seed-offgrid-inverter.jpg', '/assets/images/1789740843195-gjxobu.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Kirloskar Solar combo kit with panels, inverters and a solar battery' WHERE c.slug = 'on-off-grid-solar-combos' AND m.url IN ('/assets/images/seed-solar-combo.jpg', '/assets/images/1789740869744-aozt9n.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Microtek home and office inverter range, including Smart Hybrid models' WHERE c.slug = 'microtek-inverters' AND m.url IN ('/assets/images/seed-microtek-inverter.jpg', '/assets/images/1789741923359-m3s4lo.png');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Luminous home and office inverter range, including Eco Volt Neo and Optimus' WHERE c.slug = 'luminous-inverters' AND m.url IN ('/assets/images/seed-luminous-inverter.jpg', '/assets/images/1789741962659-hh0kps.png');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Yellow Eastman home inverters with digital displays' WHERE c.slug = 'eastman-inverters' AND m.url IN ('/assets/images/seed-eastman-inverter.jpg', '/assets/images/1789741993572-lk0oj1.png');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Amaron Quanta VRLA and tubular batteries for UPS and home backup' WHERE c.slug = 'amaron-quanta-batteries' AND m.url IN ('/assets/images/seed-amaron-battery.jpg', '/assets/images/1789742798106-o88qrz.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Exide inverter and tubular batteries, including InvaPlus and InvaMaster' WHERE c.slug = 'exide-batteries' AND m.url IN ('/assets/images/seed-exide-battery.jpg', '/assets/images/1789742805920-gbnuxz.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Eastman tubular inverter batteries, including Platinum, Immortal and Durotec' WHERE c.slug = 'eastman-batteries' AND m.url IN ('/assets/images/seed-eastman-battery.jpg', '/assets/images/1789742813278-bjcn84.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Zigma Optimus static voltage regulator for sensitive industrial machines' WHERE c.slug = 'zigma-static-voltage-regulators' AND m.url IN ('/assets/images/seed-stabilizer-optimus.png', '/assets/images/1789748395763-50ugfl.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'APC battery management controller with status LEDs on the front panel' WHERE c.slug = 'apc-battery-management-system' AND m.url IN ('/assets/images/seed-bms-apc.png', '/assets/images/1789748439157-29z4x9.webp');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Containerised utility-scale battery energy storage system (BESS)' WHERE c.slug = 'utility-scale-bess' AND m.url IN ('/assets/images/city-skyline-with-solar-panels-and-indus.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Battery energy storage with an energy management system for peak shaving' WHERE c.slug = 'peak-shaving-ems-bess' AND m.url IN ('/assets/images/solar-farm-with-wind-turbines-at-sunset-.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Blue electric car plugged into a row of DC fast-charging stations' WHERE c.slug = 'ev-charging-infrastructure' AND m.url IN ('/assets/images/blue-electric-vehicle-charging-at-a-mode.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Electric car charging at networked EV chargers outside an office building' WHERE c.slug = 'smart-ev-charging-solutions' AND m.url IN ('/assets/images/blue-electric-vehicle-charging-at-a-mode.jpg');
UPDATE catalog_media m JOIN catalog_items c ON c.id = m.item_id SET m.alt = 'Integrated rooftop solar, battery storage and EV charging system' WHERE c.slug = 'solar-bess-ev-charging' AND m.url IN ('/assets/images/city-skyline-with-solar-panels-and-indus.jpg');

-- Media library alt text for uploaded product photos (Admin → Media → Edit)
UPDATE media_assets SET alt = 'ABB PowerValue online tower UPS with LCD status display' WHERE path = '/assets/images/1789031652755-eh4bzb.webp';
UPDATE media_assets SET alt = 'APC Back-UPS Pro 700, 1000 and 1500 tower UPS units' WHERE path = '/assets/images/1789737371916-t9z0eh.webp';
UPDATE media_assets SET alt = 'Vertiv Liebert floor-standing online UPS cabinet with touchscreen display' WHERE path = '/assets/images/1789737477779-hize97.webp';
UPDATE media_assets SET alt = 'Numeric online UPS systems for commercial and industrial backup power' WHERE path = '/assets/images/1789737514668-3uq7jp.webp';
UPDATE media_assets SET alt = 'Eaton high-capacity three-phase UPS cabinet for data centres' WHERE path = '/assets/images/1789739199210-df9wes.webp';
UPDATE media_assets SET alt = 'Delta UPS range from compact tower units to modular rack cabinets' WHERE path = '/assets/images/1789739544518-20j865.webp';
UPDATE media_assets SET alt = 'Powerone three-phase online UPS cabinets in three power ratings' WHERE path = '/assets/images/1789738944653-vq0yui.webp';
UPDATE media_assets SET alt = 'Studer Xtender XTM 2600-48 hybrid inverter/charger, front view' WHERE path = '/assets/images/1789740259580-38q84z.webp';
UPDATE media_assets SET alt = 'Studer Xtender XTH hybrid inverter/charger in a grey enclosure' WHERE path = '/assets/images/1789740342301-6ajtqk.webp';
UPDATE media_assets SET alt = 'Compact Studer Xtender XTS inverter/charger in a finned aluminium case' WHERE path = '/assets/images/1789740373707-5j2c4v.webp';
UPDATE media_assets SET alt = 'Kirloskar Solar range of mono and polycrystalline solar panels' WHERE path = '/assets/images/1789740794371-sqv7ed.webp';
UPDATE media_assets SET alt = 'Kirloskar Solar on-grid string inverter for rooftop plants' WHERE path = '/assets/images/1789740813866-8wxbza.webp';
UPDATE media_assets SET alt = 'Wall-mounted Kirloskar Solar off-grid PV inverter' WHERE path = '/assets/images/1789740843195-gjxobu.webp';
UPDATE media_assets SET alt = 'Kirloskar Solar combo kit with panels, inverters and a solar battery' WHERE path = '/assets/images/1789740869744-aozt9n.webp';
UPDATE media_assets SET alt = 'Microtek home and office inverter range, including Smart Hybrid models' WHERE path = '/assets/images/1789741923359-m3s4lo.png';
UPDATE media_assets SET alt = 'Luminous home and office inverter range, including Eco Volt Neo and Optimus' WHERE path = '/assets/images/1789741962659-hh0kps.png';
UPDATE media_assets SET alt = 'Yellow Eastman home inverters with digital displays' WHERE path = '/assets/images/1789741993572-lk0oj1.png';
UPDATE media_assets SET alt = 'Amaron Quanta VRLA and tubular batteries for UPS and home backup' WHERE path = '/assets/images/1789742798106-o88qrz.webp';
UPDATE media_assets SET alt = 'Exide inverter and tubular batteries, including InvaPlus and InvaMaster' WHERE path = '/assets/images/1789742805920-gbnuxz.webp';
UPDATE media_assets SET alt = 'Eastman tubular inverter batteries, including Platinum, Immortal and Durotec' WHERE path = '/assets/images/1789742813278-bjcn84.webp';
UPDATE media_assets SET alt = 'Zigma Optimus static voltage regulator for sensitive industrial machines' WHERE path = '/assets/images/1789748395763-50ugfl.webp';
UPDATE media_assets SET alt = 'APC battery management controller with status LEDs on the front panel' WHERE path = '/assets/images/1789748439157-29z4x9.webp';

COMMIT;
